language: objective-c
xcode_project: CleanroomConcurrency.xcodeproj
osx_image: xcode8.3

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - ./BuildControl/bin/travisBuildHelper.sh build iOS
  - ./BuildControl/bin/travisBuildHelper.sh test iOS
  - ./BuildControl/bin/travisBuildHelper.sh build macOS
  - ./BuildControl/bin/travisBuildHelper.sh test macOS
  - ./BuildControl/bin/travisBuildHelper.sh build tvOS
  - ./BuildControl/bin/travisBuildHelper.sh test tvOS
  - ./BuildControl/bin/travisBuildHelper.sh build watchOS

after_failure:
  - test -f "CleanroomConcurrency-iOS-build.log" && tail -n 2500 "CleanroomConcurrency-iOS-build.log"
  - test -f "CleanroomConcurrency-iOS-test.log" && tail -n 2500 "CleanroomConcurrency-iOS-test.log"
  - test -f "CleanroomConcurrency-iOS-test.log" && LINE_BEFORE=`cat "CleanroomConcurrency-iOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "CleanroomConcurrency-iOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "CleanroomConcurrency-macOS-build.log" && tail -n 2500 "CleanroomConcurrency-macOS-build.log"
  - test -f "CleanroomConcurrency-macOS-test.log" && tail -n 2500 "CleanroomConcurrency-macOS-test.log"
  - test -f "CleanroomConcurrency-macOS-test.log" && LINE_BEFORE=`cat "CleanroomConcurrency-macOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "CleanroomConcurrency-macOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "CleanroomConcurrency-tvOS-build.log" && tail -n 2500 "CleanroomConcurrency-tvOS-build.log"
  - test -f "CleanroomConcurrency-tvOS-test.log" && tail -n 2500 "CleanroomConcurrency-tvOS-test.log"
  - test -f "CleanroomConcurrency-tvOS-test.log" && LINE_BEFORE=`cat "CleanroomConcurrency-tvOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "CleanroomConcurrency-tvOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "CleanroomConcurrency-watchOS-build.log" && tail -n 2500 "CleanroomConcurrency-watchOS-build.log"

