language: objective-c
xcode_project: CleanroomConcurrency.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail && xcodebuild -project CleanroomConcurrency.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomConcurrency-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 clean build
  - set -o pipefail && xcodebuild -project CleanroomConcurrency.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomConcurrency-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 test
  - set -o pipefail && xcodebuild -project CleanroomConcurrency.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomConcurrency-OSX -destination 'platform=macOS' -destination-timeout 300 clean build
  - set -o pipefail && xcodebuild -project CleanroomConcurrency.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomConcurrency-OSX -destination 'platform=macOS' -destination-timeout 300 test
  - set -o pipefail && xcodebuild -project CleanroomConcurrency.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomConcurrency-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 clean build
  - set -o pipefail && xcodebuild -project CleanroomConcurrency.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomConcurrency-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 test
  - set -o pipefail && xcodebuild -project CleanroomConcurrency.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomConcurrency-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' -destination-timeout 300 clean build
